# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  serviceConnection : 'sc-azure'
  appName: 'azwebappconteneur'
  containerRegistry: 'acrdemodas.azurecr.io'
  acrServiceConnection : 'sc-container-registry-2'
  imageRepository: 'democours'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage : 'Build' 
  displayName:  'Génération et push image'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job : 'Build'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: '$(acrServiceConnection)'
          repository: '$(imageRepository)'
          command: 'buildAndPush'
          Dockerfile: '$(dockerfilePath)'
          buildContext: '$(Build.SourcesDirectory)'
        displayName: 'Génération et push image dans registre de conteneurs'

- stage : 'DeployToDev' 
  displayName:  'Déploiment en Dev'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: 'Build'
  jobs:
    - deployment : 'DeployToDev'
      environment: 'Dev'
      strategy:
        runOnce:
         deploy:
           steps:
           - task: AzureWebAppContainer@1
             inputs:
               azureSubscription: '$(serviceConnection)'
               appName: '$(appName)'
               containers: '$(containerRegistry)/$(imageRepository):$(tag)'
             displayName: 'Déploiement sur Azure Web App For Container'
